char style_css[] =
	"/* ============================================================\n"
	"   MultiCS r1000 v1.28 - Stats Tiles Theme (Side Menu)\n"
	"   by Sharillas@2026 - external stylesheet (FILE STYLESHEET)\n"
	"   ============================================================ */\n"
	"* { margin:0; padding:0; box-sizing:border-box; }\n"
	"html { background:#1e232b; color-scheme:dark; }\n"
	"body {\n"
	"  font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif;\n"
	"  font-size:15px; font-weight:500; background:#1e232b; color:#e4e9f1;\n"
	"  min-height:100vh; padding-left:224px;\n"
	"}\n"
	"\n"
	"/* ---------- links ---------- */\n"
	"a { font-family:'Segoe UI',Tahoma,sans-serif; font-size:13px; font-weight:600; }\n"
	"a:link, a:visited { text-decoration:none; color:#7dd3fc; }\n"
	"a:hover { text-decoration:none; color:#a5e3ff; }\n"
	"a:active { text-decoration:none; color:#7dd3fc; }\n"
	"\n"
	"/* ---------- SIDE MENU ---------- */\n"
	".menu {\n"
	"  position:fixed; top:0; left:0; bottom:0; width:224px; z-index:900;\n"
	"  background:#262c35; border-right:1px solid #363d48;\n"
	"  padding:0; display:flex; flex-direction:column; overflow-y:auto;\n"
	"}\n"
	".menu ul { list-style:none; display:flex; flex-direction:column; gap:2px; padding:14px 10px 10px 10px; flex:1; }\n"
	".menu li { list-style:none; display:block; }\n"
	".menu li.menu-right { margin-top:auto; padding-top:10px; border-top:1px solid #363d48; display:flex; flex-direction:column; gap:6px; align-items:stretch; }\n"
	".menu li.menu-right a, .menu li.menu-right button { text-align:center; }\n"
	"a.mbtn, a.mbtn:link, a.mbtn:visited {\n"
	"  display:block; padding:10px 14px; border-radius:8px;\n"
	"  font:600 13px 'Segoe UI',Tahoma,sans-serif; color:#a5aeba !important;\n"
	"  border-left:3px solid transparent; transition:all .15s; text-shadow:none;\n"
	"}\n"
	"a.mbtn:hover { background:#303741; color:#fff !important; }\n"
	"a.mbtn.on {\n"
	"  background:#2f3642; color:#7dd3fc !important; border-left-color:#0ea5e9;\n"
	"  font-weight:700;\n"
	"}\n"
	"a.mbtn.off { color:#5a6270 !important; cursor:not-allowed; }\n"
	".menu .badge-count { float:right; background:#0ea5e9; color:#fff; border-radius:20px; padding:0 8px; font-size:11px; font-weight:700; }\n"
	"a.mbtn.on .badge-count { background:#38d0f0; color:#0b1a22; }\n"
	".brand-line { padding:12px 16px; border-top:1px solid #363d48; }\n"
	".brand { color:#7dd3fc; font-weight:800; font-size:15px; letter-spacing:.5px; }\n"
	".brand-by { color:#6b7484; font-size:11.5px; }\n"
	"\n"
	"/* ---------- layout base ---------- */\n"
	".toolbar {\n"
	"  position:sticky; top:0; z-index:500;\n"
	"  padding:10px 18px;\n"
	"  background:#242a33; border-bottom:1px solid #363d48;\n"
	"  display:flex; align-items:center; gap:12px; color:#9aa4b2; font-size:13px;\n"
	"  backdrop-filter:blur(6px);\n"
	"}\n"
	".toolbar input[type=range] { accent-color:#0ea5e9; flex:0 1 220px; }\n"
	".toolbar-label { color:#9aa4b2; font-weight:600; }\n"
	".toolbar-badge { background:#2f3642; color:#7dd3fc; padding:2px 12px; border-radius:14px; font-weight:700; font-size:12px; }\n"
	"#mainDiv { margin-left:12px; margin-right:12px; padding:14px 6px 20px 6px; min-height:100vh; }\n"
	"\n"
	"/* ---------- base elements ---------- */\n"
	"td { border-width:0; font-family:'Segoe UI',Tahoma,sans-serif; font-size:12px; font-weight:500; padding:4px 6px; color:#e4e9f1; }\n"
	"th { font-family:'Segoe UI',Tahoma,sans-serif; }\n"
	"textarea {\n"
	"  border:1px solid #3a414d; border-radius:8px; width:100%; height:81%;\n"
	"  margin:5px 0; padding:8px; font-family:Consolas,monospace; font-size:12px;\n"
	"  background:#191d24; color:#e4e9f1;\n"
	"}\n"
	"fieldset { border:1px solid #363d48; border-radius:12px; padding:12px; margin:12px 0; background:#242a33; }\n"
	"legend { font-weight:bold; color:#7dd3fc; padding:0 10px; }\n"
	"\n"
	"/* ---------- forms (especial atencao: drop-downs + uploads) ---------- */\n"
	"input, textarea, select {\n"
	"  padding:6px 10px; border:1px solid #3a414d; border-radius:8px;\n"
	"  background:#191d24; color:#e4e9f1;\n"
	"  font-family:'Segoe UI',Tahoma,sans-serif; font-size:13px;\n"
	"  transition:border-color .2s, box-shadow .2s;\n"
	"}\n"
	"input:hover, select:hover, textarea:hover { border-color:#4a5568; }\n"
	"input:focus, select:focus, textarea:focus {\n"
	"  outline:none; border-color:#0ea5e9; box-shadow:0 0 0 3px rgba(14,165,233,0.18);\n"
	"}\n"
	"/* drop-downs */\n"
	"select { cursor:pointer; padding-right:30px;\n"
	"  background-image:linear-gradient(45deg,transparent 50%,#7dd3fc 50%),linear-gradient(135deg,#7dd3fc 50%,transparent 50%);\n"
	"  background-position:calc(100% - 16px) 55%,calc(100% - 11px) 55%;\n"
	"  background-size:5px 5px; background-repeat:no-repeat;\n"
	"  -webkit-appearance:none; appearance:none;\n"
	"}\n"
	"select option { background:#242a33; color:#e4e9f1; }\n"
	"/* upload de ficheiros */\n"
	"input[type=file] { padding:5px; background:#242a33; border:1px dashed #4a5568; cursor:pointer; }\n"
	"input[type=file]::file-selector-button {\n"
	"  background:#2f3642; color:#e4e9f1; border:1px solid #3a414d; border-radius:8px;\n"
	"  padding:6px 14px; margin-right:10px; font:600 12px 'Segoe UI',sans-serif; cursor:pointer;\n"
	"  transition:background .15s;\n"
	"}\n"
	"input[type=file]::file-selector-button:hover { background:#0ea5e9; color:#fff; border-color:#0ea5e9; }\n"
	"\n"
	"/* ---------- botoes ---------- */\n"
	".sbutton, input[type=submit], input[type=button], button {\n"
	"  background:#2f3642; color:#e4e9f1; border:1px solid #3a414d; border-radius:8px;\n"
	"  padding:7px 16px; font:600 12px 'Segoe UI',Tahoma,sans-serif; cursor:pointer;\n"
	"  transition:background .15s, border-color .15s;\n"
	"}\n"
	".sbutton:hover, input[type=submit]:hover, input[type=button]:hover, button:hover {\n"
	"  background:#0ea5e9; border-color:#0ea5e9; color:#fff;\n"
	"}\n"
	".icobtn { display:inline-block; margin:0 2px; padding:3px 10px; border-radius:6px; border:1px solid #3a414d; background:#2f3642; color:#e4e9f1; }\n"
	".icobtn:hover { background:#0ea5e9; border-color:#0ea5e9; color:#fff; }\n"
	".btn-del { background:transparent; color:#fb8080; border:1px solid #7a3a3a; border-radius:6px; padding:2px 10px; }\n"
	".btn-del:hover { background:rgba(251,128,128,0.15); color:#fb8080; border-color:#fb8080; }\n"
	".cfgbtns { display:flex; flex-wrap:wrap; gap:10px; align-items:stretch; }\n"
	".cfgbtns .cfgitem { flex:1 1 200px; min-width:200px; }\n"
	".cfgbtns .cfgitem .sbutton, .cfgbtns .cfgitem a.sbutton { display:block; width:100%; text-align:center; white-space:nowrap; overflow:hidden; text-overflow:ellipsis; }\n"
	".cfgbtns-info { display:inline-block; margin:4px 4px 4px 0; padding:6px 14px; border-radius:8px; background:#2f3642; border:1px solid #3a414d; color:#e4e9f1; }\n"
	".cfgbtns-info:hover { background:#0ea5e9; border-color:#0ea5e9; color:#fff; }\n"
	".logout-btn, .logout-btn:link, .logout-btn:visited {\n"
	"  display:inline-block; padding:8px 16px; border-radius:8px;\n"
	"  border:1px solid #7a3a3a; background:transparent; color:#fb8080;\n"
	"  font:600 12px 'Segoe UI',sans-serif; text-decoration:none;\n"
	"  transition:background .15s; vertical-align:middle;\n"
	"}\n"
	".logout-btn:hover { background:rgba(251,128,128,0.15); color:#fb8080; }\n"
	"#themeToggle { background:transparent; color:#7dd3fc; border:1px solid #3a4a5d; }\n"
	"#themeToggle:hover { background:rgba(125,211,252,0.12); color:#a5e3ff; border-color:#7dd3fc; }\n"
	"\n"
	"/* ---------- ON/OFF switches (especial atencao) ---------- */\n"
	".sw { display:inline-block; min-width:44px; text-align:center; padding:2px 10px; border-radius:14px; font:700 11px 'Segoe UI',sans-serif; }\n"
	".sw-on { background:rgba(70,220,160,0.15); color:#46dca0; border:1px solid rgba(70,220,160,0.5); }\n"
	".sw-off { background:rgba(251,128,128,0.12); color:#fb8080; border:1px solid rgba(251,128,128,0.4); }\n"
	"\n"
	"/* ---------- tabelas ---------- */\n"
	".maintable, .infotable, table.option {\n"
	"  width:100%; border-collapse:collapse; border-radius:10px; overflow:hidden;\n"
	"}\n"
	".maintable th, .infotable th, table.option th {\n"
	"  background:#2f3642; color:#9aa4b2; font-size:12px; font-weight:600;\n"
	"  text-align:left; padding:9px 10px; border-bottom:1px solid #363d48;\n"
	"}\n"
	".maintable td, .infotable td, table.option td { padding:8px 10px; font-size:12.5px; border-bottom:1px solid #2c333e; }\n"
	".maintable tr:hover td { background:#29303a; }\n"
	"tr.alt1 td { background:#262d37; }\n"
	"tr.alt2 td { background:#232a33; }\n"
	".maintable td.left { text-align:left; }\n"
	".maintable td.right { text-align:right; }\n"
	".maintable th { cursor:pointer; }\n"
	".cwcol { font-family:Consolas,monospace; color:#ffc94d; font-size:11.5px; letter-spacing:.5px; }\n"
	".cwcell { font-family:Consolas,monospace; }\n"
	".cwtable { border:1px solid #363d48; }\n"
	"\n"
	"/* ---------- cores de estado ---------- */\n"
	".success { color:#46dca0; font-weight:700; }\n"
	".failed { color:#9aa4b2; font-weight:700; }\n"
	".busy { color:#ffc94d; font-weight:700; }\n"
	".online { color:#46dca0; font-weight:700; }\n"
	".offline { color:#fb8080; font-weight:700; }\n"
	"/* linhas coloridas por estado (JS colorStatusRows) */\n"
	"tr.row-offline td { background:rgba(251,128,128,0.09) !important; }\n"
	"tr.row-offline td.offline { color:#fb8080 !important; font-weight:700; }\n"
	"tr.row-online td { background:rgba(70,220,160,0.05) !important; }\n"
	"tr.row-busy td { background:rgba(255,201,77,0.08) !important; }\n"
	".new { color:#38d0f0; font-weight:700; }\n"
	".miss { color:#fb8080; font-weight:700; }\n"
	".smsdot { display:inline-block; width:8px; height:8px; border-radius:50%; background:#ffc94d; box-shadow:0 0 8px #ffc94d; }\n"
	".on { color:#46dca0; font-weight:700; }\n"
	".off { color:#8a94a6; }\n"
	".dbg { color:#7dd3fc; }\n"
	".dbginfo { color:#9aa4b2; font-size:11.5px; }\n"
	".inf { color:#a5e3ff; }\n"
	"\n"
	"/* ---------- badges ---------- */\n"
	".badge-count { background:#0ea5e9; color:#fff; border-radius:20px; padding:0 8px; font-size:11px; font-weight:700; }\n"
	".badge-green { background:rgba(70,220,160,0.15); color:#46dca0; border:1px solid rgba(70,220,160,0.4); border-radius:20px; padding:0 8px; font-size:11px; font-weight:700; }\n"
	".badge-blue { background:rgba(56,208,240,0.15); color:#38d0f0; border:1px solid rgba(56,208,240,0.4); border-radius:20px; padding:0 8px; font-size:11px; font-weight:700; }\n"
	".badge-gray { background:#2f3642; color:#9aa4b2; border:1px solid #363d48; border-radius:20px; padding:0 8px; font-size:11px; font-weight:700; }\n"
	"\n"
	"/* ---------- cards / stat sections ---------- */\n"
	".stat-section {\n"
	"  background:#242a33; border:1px solid #363d48; border-radius:14px;\n"
	"  padding:16px 18px; margin-bottom:14px;\n"
	"}\n"
	".stitle {\n"
	"  margin:0 0 10px; font-size:12px; letter-spacing:1.5px; text-transform:uppercase;\n"
	"  color:#7dd3fc; border-bottom:1px solid #363d48; padding-bottom:8px;\n"
	"}\n"
	".stat-value { color:#e4e9f1; }\n"
	".stat-value2 { color:#46dca0; font-weight:700; }\n"
	".stat-label { color:#9aa4b2; font-weight:600; }\n"
	"\n"
	"/* ---------- tiles do dashboard ---------- */\n"
	".trow { display:flex; gap:12px; flex-wrap:wrap; margin-bottom:14px; }\n"
	".tile { flex:1; min-width:160px; background:linear-gradient(160deg,#2a303a,#232830);\n"
	"  border:1px solid #3a414d; border-radius:14px; padding:14px 16px; }\n"
	".tile .big { font-size:28px; font-weight:800; margin:2px 0; line-height:1.15; }\n"
	".tile .lbl { font-size:11px; letter-spacing:1px; text-transform:uppercase; color:#9aa4b2; }\n"
	".tile .sub { font-size:11.5px; color:#9aa4b2; }\n"
	".c-cyan { color:#38d0f0; } .c-violet { color:#b19aff; } .c-green { color:#46dca0; }\n"
	".c-amber { color:#ffc94d; } .c-red { color:#9aa4b2; } .c-blue { color:#6cb0ff; }\n"
	"\n"
	"/* ---------- barras ---------- */\n"
	".bar { height:8px; border-radius:5px; background:#323945; overflow:hidden; display:inline-block; vertical-align:middle; }\n"
	".bar i { display:block; height:100%; border-radius:5px; }\n"
	"\n"
	"/* ---------- cards chips (CAID:PROVID) ---------- */\n"
	".cardchip { display:inline-block; margin:1px 2px 1px 0; padding:1px 7px; border-radius:6px;\n"
	"  font:700 11px Consolas,monospace; border:1px solid #363d48; background:#2f3642; color:#9aa4b2; }\n"
	".chip-1814 { color:#38d0f0; border-color:#38d0f055; background:#38d0f012; }\n"
	".chip-1802 { color:#b19aff; border-color:#b19aff55; background:#b19aff12; }\n"
	".chip-0624 { color:#46dca0; border-color:#46dca055; background:#46dca012; }\n"
	".chip-1830 { color:#ffc94d; border-color:#ffc94d55; background:#ffc94d12; }\n"
	".chip-1843 { color:#fb8080; border-color:#fb808055; background:#fb808012; }\n"
	".chip-1803 { color:#6cb0ff; border-color:#6cb0ff55; background:#6cb0ff12; }\n"
	".prov { font:600 10.5px 'Segoe UI',sans-serif; color:#9aa4b2; margin-right:4px; }\n"
	".hop { color:#9aa4b2; font-size:11.5px; }\n"
	"\n"
	"/* ---------- debug log (especial atencao) ---------- */\n"
	"pre {\n"
	"  background:#191d24; border:1px solid #363d48; border-radius:10px;\n"
	"  padding:12px; font:12px Consolas,monospace; color:#a5ecb8; white-space:pre-wrap;\n"
	"  max-height:420px; overflow-y:auto;\n"
	"}\n"
	"#dbglog { max-height:480px; }\n"
	"\n"
	"/* ---------- login ---------- */\n"
	".login-page { position:fixed; inset:0; display:flex; align-items:center; justify-content:center; background:#1e232b; padding:0 !important; }\n"
	".login-box { background:#242a33; border:1px solid #363d48; border-radius:16px; padding:28px 32px; min-width:320px; box-shadow:0 10px 40px rgba(0,0,0,0.4); }\n"
	".login-box .brand { font-size:18px; }\n"
	".login-error { color:#fb8080; font-weight:700; }\n"
	"\n"
	"/* ---------- footer ---------- */\n"
	".home-footer { padding:14px 2px; margin-top:14px; border-top:1px solid #363d48; }\n"
	".hf-ver { color:#6b7484; font-size:12px; }\n"
	"html.light-mode .home-footer { border-top-color:#dfe3ea; }\n"
	"\n"
	"/* ---------- scrollbars ---------- */\n"
	"::-webkit-scrollbar { width:10px; height:10px; }\n"
	"::-webkit-scrollbar-track { background:#1e232b; }\n"
	"::-webkit-scrollbar-thumb { background:#3a414d; border-radius:6px; }\n"
	"::-webkit-scrollbar-thumb:hover { background:#4a5568; }\n"
	"\n"
	"/* ---------- ecra pequeno: menu vira topo ---------- */\n"
	"@media (max-width: 860px) {\n"
	"  .menu { position:static; width:100%; max-height:300px; border-right:none; border-bottom:1px solid #363d48; }\n"
	"  .menu ul { flex-direction:column; }\n"
	"  body { padding-left:0; }\n"
	"  .toolbar, #mainDiv { margin-left:0; }\n"
	"  .login-page { position:static; min-height:100vh; }\n"
	"  .menu li.menu-right { flex-direction:row; flex-wrap:wrap; }\n"
	"  .tile { min-width:120px; }\n"
	"}\n"
	"\n"
	"/* ============================================================\n"
	"   LIGHT MODE\n"
	"   ============================================================ */\n"
	"html.light-mode { background:#eef1f6; color-scheme:light; }\n"
	"body.light-mode { background:#eef1f6; color:#24272e; }\n"
	"body.light-mode a:link, body.light-mode a:visited { color:#2563eb; }\n"
	"body.light-mode a:hover, body.light-mode a:active { color:#0ea5e9; }\n"
	"body.light-mode td { color:#24272e; }\n"
	"\n"
	"body.light-mode .menu { background:#ffffff; border-right-color:#dfe3ea; box-shadow:2px 0 10px rgba(30,40,90,0.05); }\n"
	"body.light-mode a.mbtn, body.light-mode a.mbtn:link, body.light-mode a.mbtn:visited { color:#6b7280 !important; }\n"
	"body.light-mode a.mbtn:hover { background:#f1f5f9; color:#111827 !important; }\n"
	"body.light-mode a.mbtn.on { background:#e0f2fe; color:#0369a1 !important; border-left-color:#0ea5e9; }\n"
	"body.light-mode a.mbtn.off { color:#b3bac5 !important; }\n"
	"body.light-mode .menu .badge-count { background:#0ea5e9; color:#fff; }\n"
	"body.light-mode .brand { color:#0369a1; }\n"
	"body.light-mode .brand-by { color:#8a94a3; }\n"
	"body.light-mode .brand-line { border-top-color:#e2e6ee; }\n"
	"body.light-mode .menu li.menu-right { border-top-color:#e2e6ee; }\n"
	"\n"
	"body.light-mode .toolbar { background:#ffffff; border-bottom-color:#dfe3ea; color:#6b7280; }\n"
	"body.light-mode .toolbar-badge { background:#e0f2fe; color:#0369a1; }\n"
	"body.light-mode .toolbar-label { color:#6b7280; }\n"
	"\n"
	"body.light-mode input, body.light-mode textarea, body.light-mode select,\n"
	"body.light-mode input[type=file] { background:#fafbfc; color:#24272e; border-color:#cbd2dc; }\n"
	"body.light-mode select option { background:#ffffff; color:#24272e; }\n"
	"body.light-mode input[type=file]::file-selector-button { background:#e2e6ee; color:#111827; border-color:#cbd2dc; }\n"
	"body.light-mode input[type=file]::file-selector-button:hover { background:#0ea5e9; color:#fff; border-color:#0ea5e9; }\n"
	"body.light-mode input:focus, body.light-mode select:focus, body.light-mode textarea:focus { border-color:#0ea5e9; }\n"
	"\n"
	"body.light-mode .sbutton, body.light-mode input[type=submit], body.light-mode input[type=button],\n"
	"body.light-mode button { background:#e2e6ee; color:#111827; border-color:#cbd2dc; }\n"
	"body.light-mode .sbutton:hover, body.light-mode input[type=submit]:hover,\n"
	"body.light-mode input[type=button]:hover, body.light-mode button:hover { background:#0ea5e9; color:#fff; border-color:#0ea5e9; }\n"
	"body.light-mode .icobtn { background:#e2e6ee; color:#111827; border-color:#cbd2dc; }\n"
	"body.light-mode .icobtn:hover { background:#0ea5e9; color:#fff; border-color:#0ea5e9; }\n"
	"body.light-mode .cfgbtns, body.light-mode .cfgbtns-info { background:#e2e6ee; color:#111827; border-color:#cbd2dc; }\n"
	"body.light-mode .cfgbtns-info:hover { background:#0ea5e9; color:#fff; border-color:#0ea5e9; }\n"
	"body.light-mode .logout-btn, body.light-mode .logout-btn:link, body.light-mode .logout-btn:visited { border-color:#e3a0a0; color:#dc2626; }\n"
	"body.light-mode .logout-btn:hover { background:rgba(220,38,38,0.10); color:#dc2626; }\n"
	"body.light-mode #themeToggle { background:transparent; color:#0369a1; border-color:#b6d4e8; }\n"
	"body.light-mode #themeToggle:hover { background:rgba(14,165,233,0.10); color:#0ea5e9; border-color:#0ea5e9; }\n"
	"\n"
	"body.light-mode .sw-on { background:rgba(5,150,105,0.12); color:#059669; border-color:rgba(5,150,105,0.45); }\n"
	"body.light-mode .sw-off { background:rgba(220,38,38,0.08); color:#dc2626; border-color:rgba(220,38,38,0.35); }\n"
	"\n"
	"body.light-mode .maintable th, body.light-mode .infotable th, body.light-mode table.option th {\n"
	"  background:#f6f8fb; color:#6b7280; border-bottom-color:#e2e6ee;\n"
	"}\n"
	"body.light-mode .maintable td, body.light-mode .infotable td, body.light-mode table.option td { border-bottom-color:#eef1f6; }\n"
	"body.light-mode .maintable tr:hover td { background:#f1f5f9; }\n"
	"body.light-mode tr.alt1 td { background:#fafbfd; }\n"
	"body.light-mode tr.alt2 td { background:#f4f6fa; }\n"
	"body.light-mode .cwcol { color:#d97706; }\n"
	"body.light-mode .cwtable { border-color:#e2e6ee; }\n"
	"\n"
	"body.light-mode .success { color:#059669; }\n"
	"body.light-mode .failed, body.light-mode .miss { color:#dc2626; }\n"
	"body.light-mode .busy { color:#d97706; }\n"
	"body.light-mode .online { color:#059669; }\n"
	"body.light-mode .offline { color:#dc2626; }\n"
	"body.light-mode tr.row-offline td { background:rgba(220,38,38,0.07) !important; }\n"
	"body.light-mode tr.row-offline td.offline { color:#dc2626 !important; font-weight:700; }\n"
	"body.light-mode tr.row-online td { background:rgba(5,150,105,0.05) !important; }\n"
	"body.light-mode tr.row-busy td { background:rgba(217,119,6,0.08) !important; }\n"
	"body.light-mode .new { color:#0891b2; }\n"
	"body.light-mode .on { color:#059669; }\n"
	"body.light-mode .off { color:#8a94a3; }\n"
	"body.light-mode .dbg { color:#0369a1; }\n"
	"body.light-mode .dbginfo { color:#8a94a3; }\n"
	"body.light-mode .inf { color:#0891b2; }\n"
	"\n"
	"body.light-mode .badge-count { background:#0ea5e9; color:#fff; }\n"
	"body.light-mode .badge-green { background:rgba(5,150,105,0.12); color:#059669; border-color:rgba(5,150,105,0.4); }\n"
	"body.light-mode .badge-blue { background:rgba(8,145,178,0.12); color:#0891b2; border-color:rgba(8,145,178,0.4); }\n"
	"body.light-mode .badge-gray { background:#eef1f6; color:#6b7280; border-color:#dfe3ea; }\n"
	"\n"
	"body.light-mode .stat-section { background:#ffffff; border-color:#e2e6ee; box-shadow:0 3px 12px rgba(30,40,90,0.06); }\n"
	"body.light-mode .stitle { color:#0ea5e9; border-bottom-color:#e2e6ee; }\n"
	"body.light-mode .stat-value { color:#111827; }\n"
	"body.light-mode .stat-value2 { color:#059669; }\n"
	"body.light-mode .stat-label { color:#6b7280; }\n"
	"\n"
	"body.light-mode .tile { background:#ffffff; border-color:#e2e6ee; box-shadow:0 3px 12px rgba(30,40,90,0.06); }\n"
	"body.light-mode .tile .lbl, body.light-mode .tile .sub { color:#8a94a3; }\n"
	"body.light-mode .c-cyan { color:#0891b2; } body.light-mode .c-violet { color:#7c3aed; }\n"
	"body.light-mode .c-green { color:#059669; } body.light-mode .c-amber { color:#d97706; }\n"
	"body.light-mode .c-red { color:#dc2626; } body.light-mode .c-blue { color:#2563eb; }\n"
	"body.light-mode .bar { background:#e8ecf3; }\n"
	"body.light-mode .prov, body.light-mode .hop { color:#8a94a3; }\n"
	"body.light-mode .cardchip { background:#eef1f6; border-color:#dfe3ea; color:#6b7280; }\n"
	"body.light-mode .chip-1814 { color:#0891b2; border-color:#0891b255; background:#0891b20e; }\n"
	"body.light-mode .chip-1802 { color:#7c3aed; border-color:#7c3aed55; background:#7c3aed0e; }\n"
	"body.light-mode .chip-0624 { color:#059669; border-color:#05966955; background:#0596690e; }\n"
	"body.light-mode .chip-1830 { color:#d97706; border-color:#d9770655; background:#d977060e; }\n"
	"body.light-mode .chip-1843 { color:#dc2626; border-color:#dc262655; background:#dc26260e; }\n"
	"body.light-mode .chip-1803 { color:#2563eb; border-color:#2563eb55; background:#2563eb0e; }\n"
	"\n"
	"body.light-mode pre { background:#1f2937; border-color:#dfe3ea; color:#b9e6c3; }\n"
	"body.light-mode fieldset { background:#ffffff; border-color:#e2e6ee; }\n"
	"body.light-mode legend { color:#0ea5e9; }\n"
	"\n"
	"body.light-mode .login-page { background:#eef1f6; }\n"
	"body.light-mode .login-box { background:#ffffff; border-color:#e2e6ee; box-shadow:0 10px 40px rgba(30,40,90,0.15); }\n"
	"body.light-mode .login-error { color:#dc2626; }\n"
	"body.light-mode .home-footer { border-top-color:#dfe3ea; }\n"
	"body.light-mode .hf-ver { color:#8a94a3; }\n"
	"\n"
	"body.light-mode ::-webkit-scrollbar-track { background:#eef1f6; }\n"
	"body.light-mode ::-webkit-scrollbar-thumb { background:#cbd2dc; }\n"
	"body.light-mode ::-webkit-scrollbar-thumb:hover { background:#b3bac5; }\n"
	"\n"
	"/* ============================================================\n"
	"   CW FEED (painel DBG - estudo de CWs, v1.28)\n"
	"   ============================================================ */\n"
	"tr.dbgrow td { background:#151a21; padding:8px; border-radius:8px; }\n"
	"body.light-mode tr.dbgrow td { background:#eef1f6; }\n"
	".cwfeedbox { margin-top:8px; }\n"
	".cwfeed { border:1px solid #2a323e; border-radius:8px; padding:6px; background:#151a21; font-size:11px; max-height:360px; overflow-y:auto; overflow-x:hidden; }\n"
	".cwfeed-head, .cwfeed-row { display:grid; grid-template-columns:44px 300px 1fr 1fr 62px 46px 58px; gap:6px; align-items:center; }\n"
	".cwfeed-head { font-weight:700; color:#0ea5e9; border-bottom:1px solid #2a323e; padding-bottom:4px; margin-bottom:4px; position:sticky; top:0; background:#151a21; }\n"
	".cwfeed-row { padding:2px 0; border-bottom:1px dashed #2a323e; font-family:Consolas,'Courier New',monospace; }\n"
	".cwfeed-row:last-child { border-bottom:none; }\n"
	".cwfeed-e, .cwfeed-c { letter-spacing:0.5px; word-break:break-all; }\n"
	".cwfeed-ok .cwfeed-s { color:#46dca0; font-weight:700; }\n"
	".cwfeed-ok .cwfeed-c { color:#46dca0; }\n"
	".cwfeed-nok .cwfeed-s { color:#ff6b6b; font-weight:700; }\n"
	".cwfeed-wait .cwfeed-s { color:#f0b429; }\n"
	".cwfeed-t { color:#9aa4b2; }\n"
	".cwfeed-src { color:#9aa4b2; }\n"
	".cwfeed-empty { color:#9aa4b2; padding:6px; }\n"
	"body.light-mode .cwfeed { background:#eef1f6; border-color:#d5dbe4; }\n"
	"body.light-mode .cwfeed-head { background:#eef1f6; border-color:#d5dbe4; }\n"
	"body.light-mode .cwfeed-row { border-color:#d5dbe4; }\n"
	"body.light-mode .cwfeed-t, body.light-mode .cwfeed-src, body.light-mode .cwfeed-empty { color:#8a94a3; }\n"
	"body.light-mode .cwfeed-ok .cwfeed-c { color:#059669; }\n"
	""
;

char java_file[] = "function imgrequest( url, el )\n{\n	var httpRequest;\n	try { httpRequest = new XMLHttpRequest(); }\n	catch (trymicrosoft) { try { httpRequest = new ActiveXObject('Msxml2.XMLHTTP'); } catch (oldermicrosoft) { try { httpRequest = new ActiveXObject('Microsoft.XMLHTTP'); } catch(failed) { httpRequest = false; } } }\n	if (!httpRequest) { alert('Your browser does not support Ajax.'); return false; }\n	if ( typeof(el)!='undefined' ) {\n		el.style.opacity = '0.7';\n		httpRequest.onreadystatechange = function()\n		{\n			if (httpRequest.readyState == 4) el.style.opacity = '1.0';\n		}\n	}\n	httpRequest.open('GET', url, true);\n	httpRequest.send(null);\n}\nfunction btnrequest( url, sid )\n{\n	var s = document.getElementById(sid);\n	if (s) s.innerHTML = '<span class=busy>A executar...</span>';\n	var x = new XMLHttpRequest();\n	x.open('GET', url, true);\n	x.onreadystatechange = function()\n	{\n		if (x.readyState == 4) {\n			if (x.status == 200) { if (s) s.innerHTML = x.responseText; }\n			else if (s) s.innerHTML = '<span class=failed>Erro HTTP ' + x.status + '</span>';\n		}\n	};\n	x.send(null);\n}\nfunction sortTable(el,n){var t=el.closest?el.closest('table'):null;if(!t)return;var tb=t.tBodies[0]||t;var r=t.tHead?t.tHead.rows[0].cells:t.rows[0].cells;var h=r[n];if(!h)return;var b=Array.from(tb.rows);var a=window['sortAsc']=(window['sortCol']==n)?-window['sortAsc']:1;window['sortCol']=n;b.sort(function(x,y){var p=x.cells[n].textContent.trim(),q=y.cells[n].textContent.trim();var pn=parseFloat(p),qn=parseFloat(q);return isNaN(pn)||isNaN(qn)?(p>q?1:p<q?-1:0)*a:(pn-qn)*a});b.forEach(function(r){tb.appendChild(r)});}\nfunction bindSortable(){var ts=document.querySelectorAll('table.maintable');for(var k=0;k<ts.length;k++){(function(t){var ths=t.querySelectorAll('th');for(var i=0;i<ths.length;i++){(function(n){ths[n].style.cursor='pointer';ths[n].title='Click to sort';ths[n].onclick=function(){sortTable(this,n);};})(i);}})(ts[k]);}}\nfunction fetchDebugLog(){var d=document.getElementById('dbglog');if(!d)return;var x=new XMLHttpRequest();x.open('GET','/debug?action=log',true);x.onreadystatechange=function(){if(x.readyState==4&&x.status==200){d.innerHTML=x.responseText;}};x.send(null);}\nfunction setDebugFilter(v){imgrequest('/debug?action=debug&value='+v);setTimeout(fetchDebugLog,150);}\nfunction toggleDbgRow(id,url,feed){var r=document.getElementById('dbgrow_'+id);if(r){r.parentNode.removeChild(r);window.dbgOpen=null;return;}var tr=document.getElementById('Row'+id);if(!tr)return;window.dbgOpen={id:id,url:url,feed:feed||''};var x=new XMLHttpRequest();x.open('GET',url,true);x.onreadystatechange=function(){if(x.readyState==4&&x.status==200){var t=document.createElement('tr');t.id='dbgrow_'+id;t.className='dbgrow';var c=document.createElement('td');c.colSpan=99;c.innerHTML=x.responseText;t.appendChild(c);var old=document.getElementById('dbgrow_'+id);if(old)old.parentNode.removeChild(old);tr.parentNode.insertBefore(t,tr.nextSibling);if(window.dbgOpen&&window.dbgOpen.id==id&&window.dbgOpen.feed){var f=document.createElement('div');f.id='cwfeedbox_'+id;f.className='cwfeedbox';c.appendChild(f);cwfeedPoll(id,window.dbgOpen.feed,f);}}};x.send(null);}\nfunction cwfeedPoll(id,url,el){(function tick(){var d=document.getElementById('dbgrow_'+id);if(!d){setTimeout(tick,2000);return;}var x=new XMLHttpRequest();x.open('GET',url,true);x.onreadystatechange=function(){if(x.readyState==4){if(x.status==200){if(el)el.innerHTML=x.responseText;}setTimeout(tick,2000);}};x.send(null);})();}\nfunction reopenDbg(){if(!window.dbgOpen)return;var o=window.dbgOpen;var tr=document.getElementById('Row'+o.id);var d=document.getElementById('dbgrow_'+o.id);if(tr&&!d)toggleDbgRow(o.id,o.url,o.feed);}\nfunction colorStatusRows(){var tds=document.querySelectorAll('table.maintable td.offline, table.maintable td.online, table.maintable td.busy');for(var i=0;i<tds.length;i++){var tr=tds[i].parentNode;if(!tr)continue;tr.classList.remove('row-offline');tr.classList.remove('row-online');tr.classList.remove('row-busy');if(tds[i].classList.contains('offline'))tr.classList.add('row-offline');else if(tds[i].classList.contains('online'))tr.classList.add('row-online');else tr.classList.add('row-busy');}}\nsetInterval(colorStatusRows,2000);\nfunction applyTheme(t){if(t==='light'){document.body.classList.add('light-mode');document.documentElement.classList.add('light-mode');}else{document.body.classList.remove('light-mode');document.documentElement.classList.remove('light-mode');}var btn=document.getElementById('themeToggle');if(btn){btn.textContent=(t==='light')?'Dark':'Light';}}\nfunction toggleTheme(){var cur=(document.body.classList.contains('light-mode'))?'light':'dark';var t=(cur==='light')?'dark':'light';applyTheme(t);try{localStorage.setItem('theme',t);}catch(e){}}\ndocument.addEventListener('DOMContentLoaded',function(){var t='dark';try{t=localStorage.getItem('theme')||'dark';}catch(e){}try{var q=new URLSearchParams(location.search).get('theme');if(q==='light'||q==='dark')t=q;}catch(e){}applyTheme(t);bindSortable();colorStatusRows();if(document.getElementById('dbglog'))setInterval(fetchDebugLog,2000);var d=document.getElementById('mainDiv');if(d){var f=document.createElement('div');f.className='home-footer';var vm=document.title.match(/v([0-9.]+)/);f.innerHTML=\"<span class='hf-ver'>MultiCS r1000 v\"+(vm?vm[1]:'')+\" - All Rights Reserved - Sharillas@2026</span>\";if(d.parentNode){d.parentNode.insertBefore(f,d.nextSibling);}}});\n";
